name = "galois"
version = "0.1.0"
defaultTargets = ["Galois"]

[[lean_lib]]
name = "Galois"
srcDir = "."
roots = ["group_galois"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
