name = "galois"
version = "0.1.0"
defaultTargets = ["Galois"]

[[lean_lib]]
name = "Galois"
srcDir = "."
roots = ["group_galois"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.14.0"
